public enum VfxType
{
    EnemyHit = 0,
    EnemyDeath = 1,
    PlayerLand = 4,
    PlayerJump = 5,
    PlayerHit = 6,
    Novice_BasicAttack = 7,
    Novice_Signature_Charge = 8,
    Novice_Signature_Release = 9,
    Novice_Signature_Hit = 10,
    Vanguard_BasicAttack = 11,
    Vanguard_Breaker_Charge = 12,
    Vanguard_Breaker_Release = 13,
    Vanguard_Breaker_Hit = 14,
    Vanguard_OverheadCrush_Charge = 15,
    Vanguard_OverheadCrush_Release = 16,
    Vanguard_OverheadCrush_Hit = 17,
    Vanguard_Brace = 18,
    Shade_BasicAttack = 19,
    Shade_TwinFang_Charge = 20,
    Shade_TwinFang_Release = 21,
    Shade_TwinFang_Hit = 22,
    Shade_Signature_Charge = 23,
    Shade_Signature_Release = 24,
    Shade_Signature_Hit = 25,
    Shade_Haste = 26
}
